steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-ai-dashboard-backend', './backend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-ai-dashboard-backend']

# Deploy the Docker image to Cloud Run 
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
     - 'gcloud'
     - 'run'
     - 'deploy'
     - 'cloud-ai-dashboard-backend'
     - '--image'
     - 'gcr.io/$PROJECT_ID/cloud-ai-dashboard-backend'
     - '--platform'
     - 'managed'
     - '--region'
     - 'us-central1'
     - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/cloud-ai-dashboard-backend'

options:
  logging: CLOUD_LOGGING_ONLY
